// const movie_prompts = [
//     "Do a famous pose from Titanic",
//     "Do a famous pose from Lion King",
//     "Do a famous pose from Home Alone", 
//     "Do a famous pose from The Matrix", 
//     "Do a famous pose from The Gladiator", 
//     "Do a Batman Pose", 
//     "Do a Superman Pose", 
//     "Do a Spiderman pose", 
//     "Do a Iron Man Pose", 
//     "Do a Hulk Pose", 
//     "Do a Hawkeye Pose", 
//     "Do a Black Widow Pose", 
//     "Do a Flash Pose", 
//     "Do a Wonder Woman Pose", 
//     "Do a famous pose from The Ghostbusters", 
//     "Reenact a Star Wars Scene",
//     "Reenact a Frozen scene"
// ];

// const dance_prompts = [
//     "Do the griddy",
//     "Do the Macarena", 
//     "Do the Orange Justice", 
//     "Do the Hype", 
//     "Do Take the L", 
//     "Do the Salsa", 
//     "Do the Flamenco", 
//     "Do Natu Natu", 
//     "Do Couple Dancing",
//     "Do the Chicken Dance",
//     "Do the Robot Dance",
//     "Do the Electric Slide",
//     "Do the Ride the Pony",
//     "Do the Moonwalk",
// ];
// const situations_prompts = [
//     "Your reaction to your dog eating your hw",
//     "What you would do if you were lost in space",
//     "How you would react if someone stole your favorite",
//     "Your reaction when your homie rizzez up",
//     "Your reaction when you hit a tough fade away over someone",
// ];
// const celebrations_prompts = [
//     "Do a LeBron Celebration",
//     "Do a Curry Celebration",
//     "Do a Ronaldo Celebration",
//     "Do a Messi Celebration",
//     "Do a Tom Brady Celebration",
//     "Do a Gronk Celebration",
//     "Do a Serena Williams Celebration"
// ];
// const clothing_prompts = [
//     "Date Fit",
//     "Work Out Fit",
//     "Sleep Fit",
//     "Going out Fit",
//     "Party Fit",
//     "Work Fit",
//     "Hiking Fit",
//     "Casual Fit",
//     "Formal Fit",
// ];

const master_prompts = [
    "Cozy Socks and a Good Book",
    "Your Favorite Snack Close-Up",
    "Morning Coffee or Tea Mug",
    "View from Your Window",
    "Selfie with a Peace Sign",
    "Your Desk Setup",
    "Sunset or Sunrise Sky",
    "Your Current Outfit",
    "A Quick Doodle or Sketch",
    "Your Favorite Plant",
    "Smiley Face Emoji Challenge",
    "Favorite Spot in Your Home",
    "Something Yellow in Your Day",
    "Quick Snapshot of Your Lunch",
    "Candlelit Corner",
    "A Favorite Book Opened",
    "Your Pet Doing Something Cute",
    "A Quick Nature Walk Photo",
    "Your Favorite Quote on Display",
    "A Quick Handwritten Note",
    "Something Blue in Your Surroundings",
    "Minimalist Desk Photo",
    "A Photo of Your Shoes Today",
    "A Quick Close-Up of Your Eyes",
    "Cloud Shapes in the Sky",
    "A Random Object Up Close",
    "Your Go-To Snack",
    "A Snapshot of Your Favorite Drink",
    "Your Current Mood in an Emoji",
    "A Quick Photo of Your Smile",
    "A Mini Indoor Plant",
    "Something Red in Your Day",
    "A Photo of Your Hands Doing Something",
    "Your Current View",
    "A Selfie with a Hat On",
    "Your Quick Exercise Spot",
    "Something Green in Your Day",
    "Your Favorite Blanket or Pillow",
    "A Snapshot of Your TV Show or Movie",
    "Your Favorite Fruit Up Close",
    "A Quick Photo of Your Reflection",
    "Something Purple in Your Surroundings",
    "A Snapshot of Your Computer Screen",
    "Your Current Hairstyle",
    "A Quick Photo of Your Shadow",
    "A Random Object in Your Bag",
    "Your Favorite Dessert Close-Up",
    "Your Current Writing Tool",
    "A Quick Mirror Selfie",
    "A Photo of Your Favorite Artwork",
    "A Quick Photo of Your Shoes Off",
    "Your Current Playlist",
    "A Close-Up of Your Earphones or Headphones",
    "Something Orange in Your Surroundings",
    "A Quick Snapshot of Your Bag Contents",
    "Your Favorite View Outside",
    "A Selfie with a Favorite Item of Clothing",
    "Something Silly You Spot Today",
    "A Quick Snapshot of Your Evening Snack",
    "A Photo of Your Favorite Room",
    "A Random Object in Your Fridge",
    "Your Current Desktop Wallpaper",
    "A Quick Snapshot of Your Watch or Jewelry",
    "Your Favorite Candle or Scent",
    "A Photo of Your Reflection in a Mirror",
    "A Close-Up of Your Current Hairstyle",
    "Something Sparkly in Your Day",
    "A Quick Snapshot of Your Bedside Table",
    "Your Current Desktop Setup",
    "A Photo of Your Favorite Seasonal Item",
    "A Snapshot of Your Favorite Mug Collection",
    "Something Unusual in Your Routine Today",
    "A Quick Snapshot of Your Desk Plant",
    "Your Most Used App Today",
    "A Photo of Your Hands Creating Something",
    "A Snapshot of Your Favorite View from a Window",
    "Something Soft in Your Surroundings",
    "A Selfie with a Beverage of Your Choice",
    "A Quick Snapshot of Your Notepad or Journal",
    "Your Current View While Relaxing",
    "A Photo of Your Favorite Outdoor Spot",
    "Something You Find Funny Today",
    "A Quick Close-Up of Your Current Makeup",
    "Your Favorite Spot to Take a Break",
    "A Snapshot of Your Desktop Icons",
    "Something You're Grateful for Today",
    "A Photo of Your Favorite Artistic Item",
    "A Quick Snapshot of Your Current Mood",
    "Your Current Outdoor Temperature",
    "A Selfie with a Handwritten Note",
    "Something Fresh in Your Day",
    "A Quick Snapshot of Your To-Do List",
    "Your Current View While Listening to Music",
    "A Photo of Your Favorite Coffee Spot",
    "Something Vintage in Your Surroundings",
    "A Snapshot of Your Favorite Snuggle Spot",
    "A Quick Photo of Your Current Read",
    "Your Favorite Blanket or Throw"    
];
export { master_prompts };